// ── Phase Tests — MCQs + scenario questions ──
// Pass threshold: 80%. Hard-gates progression to next phase.
const TESTS={
p1:{
  ph:'p1',name:'SQL Mastery Test',pass:0.8,xp:120,
  q:[
    {ty:'mcq',q:'You need the latest row per patient_id from a raw events table. Most robust pattern:',
      o:['SELECT DISTINCT *','GROUP BY patient_id and pick MAX(updated_at)',
         'ROW_NUMBER() OVER (PARTITION BY patient_id ORDER BY updated_at DESC) then filter rn=1',
         'LEFT JOIN the table with itself on patient_id'],c:2,
      ex:'ROW_NUMBER() picks one row deterministically per partition. GROUP BY + MAX collapses but cannot bring along other columns from that exact row without re-joining.'},
    {ty:'mcq',q:'LEFT JOIN appointments → patients. The result row count is...',
      o:['Always equal to appointments','Always equal to patients',
         '≥ appointments — duplicates if a single appointment matches multiple patients',
         'Always smaller than appointments'],c:2,
      ex:'LEFT JOIN preserves every left row and multiplies if the right side has multiple matches per join key.'},
    {ty:'mcq',q:"COUNT(*) returns 10000, COUNT(phone) returns 7200. What does this mean?",
      o:['7200 duplicate phones','2800 NULL phones — 28% null rate',
         'The query is malformed','7200 distinct phones'],c:1,
      ex:'COUNT(column) ignores NULLs. The gap is your null count. 28% missing phones is critical to flag before the data enters production.'},
    {ty:'mcq',q:'WHERE vs HAVING — which filters AFTER aggregation?',
      o:['WHERE','HAVING','Both','Neither'],c:1,
      ex:'WHERE filters rows before grouping. HAVING filters the resulting groups.'},
    {ty:'mcq',q:'DATE_TRUNC(\'month\', \'2024-03-15\') returns:',
      o:['2024-03-15','2024-03-01','2024-03-31','2024-04-01'],c:1,
      ex:'DATE_TRUNC rounds DOWN to the start of the period.'},
    {ty:'mcq',q:'A materialised view differs from a regular view because:',
      o:['It runs faster always','It stores results physically — fast reads but data can be stale until REFRESH',
         'It cannot have indexes','It uses less RAM'],c:1,
      ex:'Regular view: query re-runs every SELECT. Materialised: cached result, refreshed on schedule.'},
    {ty:'mcq',q:"COALESCE(phone_mobile, phone_home, 'unknown') returns:",
      o:['All three concatenated','The first non-NULL value','NULL if any are NULL','The last non-NULL'],c:1,
      ex:'COALESCE returns the first non-NULL argument. Standard pattern for defaulting messy data.'},
    {ty:'sc',q:"SCENARIO: Your dashboard shows 50,000 patient visits last month but the source DB shows 47,500. Visits appear duplicated. What's the FIRST thing you check?",
      o:[
        'Add SELECT DISTINCT to the dashboard query',
        'Profile the JOIN — count duplicates per join key, see if any source row matches multiple right-side rows',
        'Re-extract all data from scratch',
        'Add a HAVING clause to filter'
      ],c:1,
      ex:'Duplicates almost always come from a JOIN multiplying rows. SELECT DISTINCT hides the symptom but corrupts aggregates (a real $500 visit counted twice does not become $500 again). Profile first — find the join key with multiple right-side matches, then fix the JOIN or deduplicate the right side.'},
    {ty:'sc',q:"SCENARIO: A LEFT JOIN patients → visits should keep all patients. But your no-show analysis (WHERE visit.status = 'no_show') returns zero rows for patients with no visit. Why?",
      o:[
        'The LEFT JOIN is wrong',
        "The WHERE turns the LEFT JOIN into an INNER JOIN — visit.status is NULL for unmatched rows, fails the equality check",
        "The status column is corrupted",
        "Use RIGHT JOIN instead"
      ],c:1,
      ex:"Filter conditions on the right-side table in WHERE eliminate NULL rows — silently converting LEFT JOIN to INNER JOIN. Fix: move the predicate into the ON clause, or use WHERE visit.status = 'no_show' OR visit.status IS NULL."},
    {ty:'sc',q:'SCENARIO: A 50M-row visits table query takes 12 minutes. You add an index on visit_date. Query is still slow. Most likely reason:',
      o:[
        'Indexes do not help on large tables',
        "Your WHERE uses a function: WHERE DATE_TRUNC('month',visit_date) = ... — function on indexed column prevents index use",
        'You need to rebuild the database',
        'PostgreSQL is too old'
      ],c:1,
      ex:"Wrapping an indexed column in a function (DATE_TRUNC, LOWER, CAST) makes the index unusable — the DB cannot pre-compute the function output. Rewrite as a range: WHERE visit_date >= '2024-03-01' AND visit_date < '2024-04-01'."}
  ]
},
p2:{
  ph:'p2',name:'Python for DE Test',pass:0.8,xp:140,
  q:[
    {ty:'mcq',q:'Why is Parquet preferred over CSV in DE pipelines?',
      o:['CSV is deprecated','Columnar, compressed, schema-embedded — 5-10x smaller and faster scans',
         'Parquet supports Unicode','Parquet has built-in encryption'],c:1,
      ex:'Columnar storage means SUM(revenue) reads only the revenue column. CSV reads every column row by row.'},
    {ty:'mcq',q:"df.to_sql(name, con, if_exists='replace') does what?",
      o:['Appends rows','DROPS and recreates the table','Errors if table exists','Updates by primary key'],c:1,
      ex:"'replace' = drop + recreate. 'append' = INSERT new rows. 'fail' = error if exists."},
    {ty:'mcq',q:'In a Pipeline class with __init__, extract, transform, load, run methods — which is called when you write pipeline = Pipe(source="x")?',
      o:['run','__init__','extract','load'],c:1,
      ex:'__init__ runs at instantiation. .run() must be called explicitly.'},
    {ty:'mcq',q:'unittest.mock.patch is used to:',
      o:['Patch a security hole','Replace real API/DB calls with controlled fake responses during tests',
         'Run async tasks','Format Python files'],c:1,
      ex:'Tests should not hit real APIs. mock.patch swaps the call site with a fake.'},
    {ty:'mcq',q:'On 1M rows, df.apply(row-by-row) vs vectorised df["a"]*2:',
      o:['Same speed','Vectorised is ~100x faster — compiled C under the hood',
         'apply is faster','apply is required for math'],c:1,
      ex:'Vectorised pandas operations run in C. iterrows / apply (axis=1) loop in Python.'},
    {ty:'mcq',q:'Parameterised query (cursor.execute(sql, params)) vs f-string SQL:',
      o:['Performance','Readability','Parameterised prevents SQL injection — f-strings with user input are dangerous',
         'No difference'],c:2,
      ex:"f-string SQL with user input is a textbook injection vector. Always parameterise."},
    {ty:'mcq',q:'PySpark DataFrames over RDDs because:',
      o:['DataFrames are newer','Catalyst optimiser auto-rewrites the execution plan',
         'RDDs do not support Python','DataFrames use less RAM'],c:1,
      ex:'Catalyst rewrites your DataFrame ops into an optimal physical plan. RDDs run exactly as written.'},
    {ty:'sc',q:'SCENARIO: Your ETL pipeline crashes mid-write to PostgreSQL. The next run double-loads some rows and skips others. What architectural property is missing?',
      o:[
        'Speed',
        'Idempotency + transactions — wrap the write in BEGIN/COMMIT or use DELETE+INSERT keyed by run date',
        'Compression',
        'Type validation'
      ],c:1,
      ex:'Idempotent pipelines produce the same result no matter how many times they run. Wrap writes in transactions so partial failures ROLLBACK. Re-runs should DELETE the existing partition before INSERT.'},
    {ty:'sc',q:'SCENARIO: An external API returns paginated results (next_url field). You loop until next_url is None. After 2 weeks the loop runs for 6 hours one night. Likely cause and safest fix:',
      o:[
        'API got slower; just wait',
        'API returned a loop or removed pagination — add max_pages safety guard AND a per-page timeout',
        'Increase RAM',
        'Switch to GraphQL'
      ],c:1,
      ex:'Always add a max_pages guard and per-request timeout. Without them, a broken upstream takes your pipeline down with it. Defensive defaults: max_pages=10000, timeout=30s.'},
    {ty:'sc',q:'SCENARIO: A teammate commits .env to the repo with the BigQuery service-account JSON inside. You discover it 4 hours later. Correct response:',
      o:[
        'git rm --cached .env and push',
        'Revoke the service-account key in GCP immediately, rotate credentials, then scrub from git history (git filter-branch / BFG), then add to .gitignore',
        'Force-push over the commit',
        'Wait — GitHub repos are private'
      ],c:1,
      ex:'Treat any leaked credential as compromised the second it touches Git. Revoke first (so it cannot be used), then clean history. Removing the file alone leaves it in the commit history forever.'}
  ]
},
p3:{
  ph:'p3',name:'Warehousing & dbt Test',pass:0.8,xp:160,
  q:[
    {ty:'mcq',q:'A dbt model is fundamentally:',
      o:['A Python script','A single SELECT statement that dbt materialises as table/view',
         'A YAML schema file','A Docker container'],c:1,
      ex:'dbt wraps your SELECT in CREATE TABLE AS / CREATE VIEW AS and manages dependencies.'},
    {ty:'mcq',q:"{{ ref('stg_patients') }} in a model causes dbt to:",
      o:['Cache the query','Build stg_patients first, then this model — dependency ordering',
         'Replace the SELECT','Add an index'],c:1,
      ex:'ref() builds the DAG. dbt walks the DAG to determine build order. No manual ordering needed.'},
    {ty:'mcq',q:'A staging model in dbt best practice should:',
      o:['Join multiple sources','Lightly clean ONE source — cast, trim, rename',
         'Compute final aggregations','Implement business logic'],c:1,
      ex:'Staging = one-to-one with source. Type casts, renames, trims. Zero business logic.'},
    {ty:'mcq',q:'A not_null test in schema.yml that fails causes dbt to:',
      o:['Silently continue','Mark the test as FAIL and (by default) stop downstream models',
         'Email the team','Auto-fix the data'],c:1,
      ex:'Failed tests halt the pipeline by default. You can change severity to warn for non-critical checks.'},
    {ty:'mcq',q:'In a star schema, the fact table contains:',
      o:['Descriptive patient attributes','Numeric measurable events with FK to dimensions',
         'Only dates','Configuration'],c:1,
      ex:'fact_visits: visit_id, patient_id FK, doctor_id FK, visit_date, duration, revenue. Dimensions hold descriptive context.'},
    {ty:'mcq',q:'A dbt snapshot with check_cols=[city, phone] does what when city changes for a patient?',
      o:['Overwrites old row','Adds new row with valid_from=today, marks old row as expired',
         'Errors','Logs only'],c:1,
      ex:"This is SCD Type 2 — automatic history tracking via dbt's snapshot."},
    {ty:'mcq',q:'BigQuery partition_by on visit_date causes:',
      o:['Index creation','Physical partitions per date range — date-filtered queries scan only relevant partitions',
         'Faster INSERTs','Encryption'],c:1,
      ex:"Partition pruning is the biggest BQ cost-saver. WHERE visit_date >= ... scans only those partition files."},
    {ty:'sc',q:'SCENARIO: Your dbt project has 200 models. A change to stg_patients breaks 15 downstream marts. What does dbt provide to help diagnose?',
      o:[
        'Nothing — read each model manually',
        'dbt docs generate produces a visual lineage DAG; dbt test runs all tests; dbt run --select +mart_x shows everything stg_patients feeds into',
        'A Slack integration',
        'AI auto-fix'
      ],c:1,
      ex:"Lineage DAG is dbt's superpower. + selector means 'all ancestors'. This is why dbt scales to large teams."},
    {ty:'sc',q:'SCENARIO: A patient changes city. Your mart_patient_summary uses the LATEST city — but historical visits should be tied to the city WHERE the patient lived at visit time. What pattern fixes this?',
      o:[
        'Just use current city for everything',
        'SCD Type 2 dim_patient (dbt snapshot) joined to fact_visits on visit_date BETWEEN valid_from AND valid_to',
        'Pivot the data',
        'Store as JSON'
      ],c:1,
      ex:'Point-in-time correctness needs SCD2. Each visit joins to the row of dim_patient valid on that date. dbt snapshots automate the SCD2 mechanics.'},
    {ty:'sc',q:'SCENARIO: A junior writes business logic directly in stg_patients (filtering only "active" patients). 6 months later a new analyst joins and asks "how do I get all historical patients?" The data is gone. The root mistake:',
      o:[
        'They should have used Python',
        'Staging must be one-to-one with source. Filtering belongs in marts. Staging = lossless cleanup.',
        'They should have used a CTE',
        'Add an index'
      ],c:1,
      ex:'Staging models are the lossless contract with the source. Business filters (active, opted_in) go in marts where the rules are clear and reversible.'}
  ]
},
p4:{
  ph:'p4',name:'Orchestration Test',pass:0.8,xp:160,
  q:[
    {ty:'mcq',q:'An Airflow DAG is:',
      o:['A query','A directed acyclic graph of scheduled tasks with dependencies','A Docker image','A Python class'],c:1,
      ex:'DAG = tasks + dependencies + schedule. The fundamental unit of orchestration in Airflow.'},
    {ty:'mcq',q:'extract >> transform >> load means:',
      o:['Parallel execution','transform runs after extract; load runs after transform','Random order','All optional'],c:1,
      ex:'>> is the dependency operator. Left task must succeed before right task starts.'},
    {ty:'mcq',q:'Airflow Connections (Admin > Connections) are useful because:',
      o:['They cache queries','They store credentials centrally — DAG code is safe to commit',
         'They speed up DAGs','They auto-retry'],c:1,
      ex:'Reference by conn_id in your DAG. Actual credentials encrypted in Airflow metadata DB.'},
    {ty:'mcq',q:'An idempotent pipeline means:',
      o:['It runs fast','Multiple runs produce the same result with no duplicates','It uses minimal RAM','It never fails'],c:1,
      ex:'Idempotency is non-negotiable for production pipelines. Without it, retries corrupt data.'},
    {ty:'mcq',q:'GCSObjectExistenceSensor is useful when:',
      o:['You want to query BigQuery','Your pipeline must wait until a specific file appears in GCS',
         'You need fixed delay','You want API health checks'],c:1,
      ex:'Sensors poll for external state. Upstream drops a file → sensor passes → downstream runs.'},
    {ty:'mcq',q:'Running dbt from Airflow is commonly done with:',
      o:['Manual trigger','BashOperator running "dbt run" or Astronomer Cosmos provider',
         'Cron','Stored procedure'],c:1,
      ex:'Cosmos converts each dbt model into an Airflow task — gets you per-model retries and visibility.'},
    {ty:'mcq',q:'A pipeline needs to alert doctors within 30 seconds of an abnormal lab result. Best architecture:',
      o:['Daily batch','Kafka streaming pipeline — producer publishes events, consumer alerts',
         'Materialised view','Manual review'],c:1,
      ex:'30 seconds = streaming requirement. Batch SLA of "daily" cannot meet sub-minute latency.'},
    {ty:'sc',q:'SCENARIO: Your daily DAG ran fine for 60 days, then started failing every Tuesday. Logs show "deadlock detected" on the target Postgres. Most likely root cause:',
      o:[
        'Postgres needs reboot weekly',
        'Tuesday is when another job writes to the same tables concurrently — schedule them sequentially OR use SELECT FOR UPDATE / advisory locks',
        'Add more RAM',
        'Network is flaky'
      ],c:1,
      ex:'Deadlocks are concurrency bugs. Identify the other writer (DBA can show lock waits), then either serialise via DAG dependencies or use explicit locking.'},
    {ty:'sc',q:'SCENARIO: A junior makes a DAG with one big task: extract_transform_load_all(). It runs for 4 hours. When it fails at hour 3, the whole thing reruns. The architectural fix:',
      o:[
        'Add print statements',
        'Split into discrete tasks (extract, transform, load) so Airflow retries only the failing step — and each task is idempotent',
        'Use a faster machine',
        'Run hourly instead of daily'
      ],c:1,
      ex:'Task granularity is leverage. Each task is a retry boundary. Splitting also gives per-step logs and timing.'},
    {ty:'sc',q:'SCENARIO: A streaming pipeline duplicates ~0.5% of events. Investigation shows the Kafka consumer commits offsets BEFORE writing to the database. What is the correct ordering?',
      o:[
        'Commit faster',
        'Write to DB first, then commit offset. If DB write succeeds but commit fails, you reprocess one event on restart — better duplicates than silent loss',
        'Use a different broker',
        'Disable retries'
      ],c:1,
      ex:'At-least-once delivery: write the side effect first, commit position second. Combined with idempotent writes (upsert by event_id), you get effectively-exactly-once semantics.'}
  ]
},
p5:{
  ph:'p5',name:'AI/ML Infrastructure Test',pass:0.8,xp:180,
  q:[
    {ty:'mcq',q:'A feature store solves which problem?',
      o:['Storing raw data','Inconsistent feature computation — compute once, serve to training AND inference identically',
         'Deploying models','Scheduling training'],c:1,
      ex:'Training-serving skew is the #1 silent killer of ML models. Feature stores eliminate it.'},
    {ty:'mcq',q:'A point-in-time JOIN ensures:',
      o:['Features cached','Feature values reflect only data available at that historical moment — preventing leakage',
         'Faster joins','Encrypted features'],c:1,
      ex:'Predicting March 1st no-shows must use ONLY data from before March 1st. Future leakage gives misleading training accuracy.'},
    {ty:'mcq',q:'In RAG, what is stored in the vector DB?',
      o:['LLM weights','Embedding vectors for each chunk + the chunk text','User chat history','SQL queries'],c:1,
      ex:'Query → embed → similarity search → retrieve top-k chunks → feed to LLM.'},
    {ty:'mcq',q:'Why does RAG chunk size matter?',
      o:['Storage cost only','Too big = irrelevant context dilutes prompt; too small = context fragments lost',
         'Embeddings need fixed size','LLM input length'],c:1,
      ex:'512-1024 tokens with 10-20% overlap is a reasonable default. Tune per document type.'},
    {ty:'mcq',q:'mlflow.log_metric("accuracy", 0.87) does what?',
      o:['Prints to console','Stores metric with current run_id in MLflow tracking server',
         'Trains the model','Sends Slack alert'],c:1,
      ex:'Each run has unique run_id. log_param + log_metric + log_artifact tie config, score, and outputs together.'},
    {ty:'mcq',q:'Model accuracy drops 87% → 71% over 3 months with no code changes. Most likely:',
      o:['FastAPI bug','Data drift — real-world distribution shifted from training distribution',
         'Database migration','Server RAM'],c:1,
      ex:'Models are static; the world is not. Monitor feature distributions and retrain on a cadence.'},
    {ty:'mcq',q:'FastAPI POST /predict for an ML model is:',
      o:['A batch pipeline','A real-time inference endpoint','A training job','A warehouse query'],c:1,
      ex:'@app.post("/predict") — input validated by Pydantic, model.predict() returns JSON. Standard pattern.'},
    {ty:'sc',q:'SCENARIO: Your training script computes age = today - dob. Your inference service computes age = login_time - dob. Model accuracy is 91% offline, 73% in production. Diagnose:',
      o:[
        'Model overfitted',
        'Training-serving skew — feature computed differently at train vs inference. Put age computation in a feature store / shared function used by both.',
        'Wrong loss function',
        'Database slow'
      ],c:1,
      ex:'Even tiny differences (today vs login_time, timezone, rounding) silently degrade production performance. Single source of truth for every feature.'},
    {ty:'sc',q:'SCENARIO: An ML model predicts patient no-shows. The team adds "appointment_was_cancelled" as a feature. Training accuracy jumps to 99%. What is wrong?',
      o:[
        'Nothing — celebrate',
        'Target leakage — cancellation is known AFTER the appointment date, not before. The feature is unavailable at prediction time.',
        'Model is overfitting on noise',
        'Need more data'
      ],c:1,
      ex:'When accuracy looks too good, look for leakage. Every feature must be available at prediction time, not retroactively populated.'},
    {ty:'sc',q:'SCENARIO: Your RAG chatbot answers "I don\'t know" to questions clearly covered in the docs. Embeddings look fine. The retrieval step returns relevant chunks. Likely cause:',
      o:[
        'LLM is broken',
        'Prompt template instructs the LLM to refuse if unsure — too conservative; OR retrieved chunks exceed context window and got truncated before reaching the model',
        'Vector DB is corrupted',
        'Network latency'
      ],c:1,
      ex:'When retrieval is good but generation fails: inspect the actual prompt sent to the LLM. Most "I don\'t know" failures are prompt-engineering or context-truncation issues.'}
  ]
},
p6:{
  ph:'p6',name:'Portfolio & Interview Test',pass:0.8,xp:200,
  q:[
    {ty:'mcq',q:'Best LinkedIn headline for your target role:',
      o:['Data Analyst at SEH','Data Engineer | SQL · Python · dbt · Airflow · AI/ML Pipelines | Healthcare',
         'Looking for opportunities','IT Professional'],c:1,
      ex:'Headline = target role + stack + domain. AI/ML pipelines + healthcare is your unique angle.'},
    {ty:'mcq',q:'Start a DE system design interview with:',
      o:['Name every tool','Clarify requirements: volume, latency, batch vs streaming, SLA',
         'Draw architecture immediately','Discuss cost first'],c:1,
      ex:'Framework: clarify → high-level → deep-dive → trade-offs. Process beats answer.'},
    {ty:'mcq',q:'A strong GitHub portfolio README contains:',
      o:['Just source code','Architecture diagram, what it does, how to run, tech stack, sample output',
         'A long bio','Random screenshots'],c:1,
      ex:'Recruiters spend 60 seconds. README is the first impression. Diagram > paragraphs.'},
    {ty:'mcq',q:'#1 most tested senior DE SQL topic:',
      o:['SELECT *','Window functions + deduplication patterns','CREATE TABLE','Backups'],c:1,
      ex:'ROW_NUMBER() OVER (PARTITION BY ... ORDER BY ...) appears in ~80% of senior DE interviews.'},
    {ty:'mcq',q:'Quantity vs quality in portfolio projects — which wins?',
      o:['10 messy repos','3 well-documented projects with clear architecture and run instructions',
         'Maximum stars','Most commits'],c:1,
      ex:'Recruiters and hiring managers scan. Clarity converts. 3 strong > 10 noisy.'},
    {ty:'mcq',q:'How many quality, targeted applications per week?',
      o:['1-2','5-10 tracked in a spreadsheet','50+ untracked','100+'],c:1,
      ex:'Mass-applying yields nothing. 5-10 deliberate, customised applications keep your pipeline healthy.'},
    {ty:'mcq',q:'When asked "tell me about a project" in an interview, structure your answer with:',
      o:['Stream of consciousness','STAR: Situation, Task, Action, Result — quantified',
         'Read your resume aloud','Skip to questions'],c:1,
      ex:'STAR with quantified results is universal. "Cut pipeline latency from 6h to 25min, processing 12M rows daily."'},
    {ty:'sc',q:'SCENARIO: Asked to "design a pipeline to ingest patient visit data from 50 hospital centres". You have 5 minutes. First thing you do:',
      o:[
        'Draw boxes for Kafka, BigQuery, dbt',
        'Ask: How big? How often? Batch acceptable or real-time? What are downstream consumers? SLA? Existing infra (cloud preference)?',
        'Start coding',
        'List 20 tools you know'
      ],c:1,
      ex:'Senior signal is process, not tools. Clarifying questions show you scope problems before solutioning. 50 centres × daily batch is a very different system than 50 centres × real-time.'},
    {ty:'sc',q:'SCENARIO: An interviewer asks "Why are you leaving your current job?" Your honest answer is "no DE role available there". Best framing:',
      o:[
        'Complain about manager',
        '"I have built data pipelines and a RAG system at SEH and I am ready to specialise full-time in DE + AI/ML infrastructure. My current role is broader; I want to go deeper on the data layer."',
        '"I need more money"',
        '"I am bored"'
      ],c:1,
      ex:'Frame moves toward something, not away. Acknowledge current value, articulate the specialisation you want. Hiring managers want signal that you know what you want and why.'},
    {ty:'sc',q:'SCENARIO: You get a take-home: build a pipeline ingesting a public API into a SQL DB with a small report. You have 4 hours. Spending the first 30 minutes on:',
      o:[
        'Writing code immediately',
        'Reading the prompt twice, sketching architecture, listing trade-offs, deciding scope, picking ONE happy path — THEN coding',
        'Picking the trendiest tools',
        'Asking the interviewer many questions'
      ],c:1,
      ex:"Take-homes test judgement, not LOC. A clean 70% solution with great README beats 100% spaghetti. Document trade-offs you didn't take — that signals seniority."}
  ]
}
};
